### PR TITLE
Background Suggestion - Image instead of Colour

### PR DESCRIPTION
**Pull request by kaushalvivek**
Tinted to match colour scheme, we can keep it if you guys are onboard.

### CODE REVIEW

**Comment by zubairabid** [comment]
@kaushalvivek I like the idea, but will need to work on the specifics. I think it'll work out better untinted. 

I'll try some stuff and float it by you

**Comment by kaushalvivek** [comment]
Cool, added the tint just to match the overall aesthetics.

**Comment by zubairabid** [comment]
What's your opinion on these?

opaque text

translucent text

I tried one with purple tinting, it isn't working out
purple

**Comment by kaushalvivek** [comment]
The black tint definitely looks better, finalise an image though. The crowd one here has the 105 back wall which is at an odd angle with the page.

**Comment by zubairabid** [comment]
@kaushalvivek Ok, cool

**Comment by zubairabid** [comment]
We've contacted the media team for a better image as of now.

**Pull request closed without merging**
